services:
  frontend:
    image: ghcr.io/gyrozepelix/portfolio-web:latest
    build:
      context: .
    networks:
      - traefik
    labels:
      - traefik.enable=true
      - traefik.http.routers.portfolio-website.rule=Host(`dgjalic.com`) || Host(`www.dgjalic.com`)
      - traefik.http.routers.portfolio-website.entrypoints=websecure
      - traefik.http.routers.portfolio-website.tls.certresolver=myresolver

      - traefik.http.middlewares.www-redirect.redirectregex.regex=^http://www.dgjalic.com/(.*)"
      - traefik.http.middlewares.www-redirect.redirectregex.replacement=http://dgjalic.com/$${1}"
      - traefik.http.routers.portfolio-website.middlewares=www-redirect"
    restart: on-failure

networks:
  traefik:
    driver: bridge
    name: traefik-reverse-proxy
    external: true
