services:
  frontend:
    image: ghcr.io/gyrozepelix/portfolio-web:latest
    build:
      context: .
    networks:
      - traefik
    labels:
      - traefik.enable=true

      - traefik.http.routers.portfoliowebsite.rule=Host(`dgjalic.com`) || Host(`www.dgjalic.com`)
      - traefik.http.services.portfoliowebsite.loadbalancer.server.port=80
      - traefik.http.routers.portfoliowebsite.entrypoints=websecure
      - traefik.http.routers.portfoliowebsite.tls.certresolver=myresolver

      - traefik.http.middlewares.mywwwredirect.redirectregex.regex=^https://www\.(.*)
      - traefik.http.middlewares.mywwwredirect.redirectregex.replacement=https://$${1}
      - traefik.http.routers.portfoliowebsite.middlewares=mywwwredirect
    restart: on-failure

networks:
  traefik:
    driver: bridge
    name: traefik-reverse-proxy
    external: true
